# Generated by Django 5.2.8 on 2025-12-07 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='color',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_variant', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_variant', to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='customer_phone',
            field=models.CharField(max_length=15, verbose_name='رقم الهاتف'),
        ),
    ]
