# Generated by Django 5.2.8 on 2025-12-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_cartdetail_color_cartdetail_variant_and_more'),
        ('products', '0005_alter_color_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='variant',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='variant_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_variant_color', to='products.variantcolor'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='variant_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_variant_color', to='products.variantcolor'),
        ),
    ]
