# Generated by Django 5.2.8 on 2025-11-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_deliveryfee"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="اسم العميل"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=15, verbose_name="رقم الهات ف"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "governorate",
                    models.CharField(max_length=100, verbose_name="المحافظة"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المدينة"
                    ),
                ),
                (
                    "address_line",
                    models.TextField(max_length=500, verbose_name="العنوان بالتفصيل"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="ملاحظات"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_time"]},
        ),
        migrations.RenameField(
            model_name="order",
            old_name="delivary_time",
            new_name="delivery_time",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.FloatField(default=0, verbose_name="رسوم التوصيل"),
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.FloatField(default=0, verbose_name="الخصم"),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.FloatField(default=0, verbose_name="المجموع الفرعي"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Received", "Received"),
                    ("Processed", "Processed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                default="Received",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.FloatField(blank=True, null=True, verbose_name="الإجمالي"),
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.orderaddress",
            ),
        ),
    ]
