# Generated by Django 5.2.8 on 2025-11-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderaddress_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Received", "تم الاستلام"),
                    ("Processed", "قيد المعالجة"),
                    ("Shipped", "تم الشحن"),
                    ("Delivered", "تم التوصيل"),
                ],
                default="Received",
                max_length=20,
            ),
        ),
    ]
