# Generated by Django 5.2.8 on 2025-12-03 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
        ('products', '0013_color_hex_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartdetail_color', to='products.productcolor'),
        ),
    ]
