# Generated by Django 5.2.8 on 2025-12-04 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cartdetail_color'),
        ('products', '0014_color_name_ar_color_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_color', to='products.productcolor'),
        ),
    ]
