# Generated by Django 5.2.8 on 2025-12-07 08:29

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='اسم الفئة')),
                ('name_ar', models.CharField(db_index=True, max_length=100, null=True, verbose_name='اسم الفئة')),
                ('name_en', models.CharField(db_index=True, max_length=100, null=True, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='الوصف')),
                ('description_ar', models.TextField(blank=True, max_length=500, null=True, verbose_name='الوصف')),
                ('description_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, verbose_name='أيقونة')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_ar', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='name')),
                ('name_ar', models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='name')),
                ('name_en', models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='name')),
                ('subtitle', models.TextField(blank=True, max_length=500, null=True, verbose_name='subtitle')),
                ('subtitle_ar', models.TextField(blank=True, max_length=500, null=True, verbose_name='subtitle')),
                ('subtitle_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='subtitle')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_colors')),
                ('description', models.TextField(blank=True, max_length=50000, null=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, max_length=50000, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, max_length=50000, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='العلامة التجارية')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='الفئة')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('code', models.CharField(max_length=100)),
                ('mark', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productimages', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=500, verbose_name='review')),
                ('rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='rate')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review_product', to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
