# Generated by Django 5.2.8 on 2025-12-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_cartdetail_color_cartdetail_variant_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
