# Generated by Django 5.2.8 on 2025-11-26 04:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_product_brand_product_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
