# Generated by Django 5.2.8 on 2025-12-08 09:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariant_options_productvariant_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name': 'لون', 'verbose_name_plural': 'الألوان'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id'], 'verbose_name': 'نمط منتج', 'verbose_name_plural': 'أنماط المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productvariantimage',
            options={'verbose_name': 'صورة النمط', 'verbose_name_plural': 'صور الأنماط'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'تقييم', 'verbose_name_plural': 'التقييمات'},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='color',
            field=models.ForeignKey(blank=True, help_text='اختياري - إذا كانت الصورة خاصة بلون معين', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_images', to='products.color', verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(blank=True, help_text='مثال: #ff0000', max_length=7, null=True, verbose_name='كود اللون'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم اللون'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='اسم اللون'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='اسم اللون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='العلامة التجارية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='منتج مميز'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, default='ظ…ظ†طھط¬', max_length=120, verbose_name='اسم المنتج'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='العنوان الفرعي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle_ar',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='العنوان الفرعي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='العنوان الفرعي'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود النمط'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(help_text='مثال: 3 USB + 3 منافذ', max_length=200, verbose_name='اسم النمط'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='image',
            field=models.ImageField(upload_to='variant_images', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant', verbose_name='النمط'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review_product', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='التقدير'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=500, verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_user', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.CreateModel(
            name='VariantColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='السعر')),
                ('quantity', models.IntegerField(default=0, verbose_name='الكمية')),
                ('sku', models.CharField(blank=True, help_text='رمز تعريف المنتج', max_length=50, null=True, verbose_name='SKU')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_colors', to='products.color', verbose_name='اللون')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.productvariant', verbose_name='النمط')),
            ],
            options={
                'verbose_name': 'لون النمط',
                'verbose_name_plural': 'ألوان الأنماط',
                'ordering': ['variant', 'color'],
                'unique_together': {('variant', 'color')},
            },
        ),
    ]
