# Generated by Django 5.2.8 on 2025-12-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(max_length=50000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(max_length=50000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_ar',
            field=models.TextField(max_length=500, null=True, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_en',
            field=models.TextField(max_length=500, null=True, verbose_name='subtitle'),
        ),
    ]
