# Generated by Django 5.2.8 on 2025-12-13 10:51

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productreview_delete_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="name_ar",
            field=models.CharField(
                help_text="مثال: 3 USB + 3 منافذ",
                max_length=200,
                null=True,
                verbose_name="اسم النمط",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="name_en",
            field=models.CharField(
                help_text="مثال: 3 USB + 3 منافذ",
                max_length=200,
                null=True,
                verbose_name="اسم النمط",
            ),
        ),
        migrations.AlterField(
            model_name="productvariantimage",
            name="image",
            field=models.ImageField(
                upload_to=products.models.variant_image_upload_path,
                verbose_name="الصورة",
            ),
        ),
    ]
