# Generated by Django 5.2.8 on 2025-12-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_description_ar_category_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle_ar',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='subtitle'),
        ),
    ]
