# Generated by Django 5.2.8 on 2025-12-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_color_remove_product_code_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_colors'),
        ),
    ]
