# Generated by Django 5.2.8 on 2025-12-05 08:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_color_name_ar_color_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='اسم الفئة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='اسم الفئة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='اسم الفئة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='ProductColorLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=50)),
                ('extra_price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lengths', to='products.productcolor')),
            ],
        ),
    ]
