# Generated by Django 5.2.8 on 2025-12-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_category_created_at_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorlength',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productcolorlength',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
