# Generated by Django 5.2.8 on 2025-12-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productcolorlength_extra_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductColorLength',
        ),
    ]
